spring.application.name=cyworld
spring.datasource.url=jdbc:mysql://localhost:3306/cyworld
spring.datasource.username=root
spring.datasource.password=

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

# /api-docs endpoint custom path
springdoc.api-docs.path=/api-docs

logging.level.org.springframework.web=DEBUG