spring.application.name=cyworld
spring.datasource.url=jdbc:mysql://localhost:3306/cyworld
spring.datasource.username=root
spring.datasource.password=

#springdoc.api-docs.path=/v3/api-docs
#
#springdoc.swagger-ui.path=/swagger-ui.html
#
#springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
#
#springdoc.packages-to-scan=com.hyunjoying.cyworld

logging.level.org.springframework.web=DEBUG

# JWT ??
# jwt.secret? 32??? ??? ?? ? ?? ?????? ?
# ???? openssl rand -base64 32 ???? ??? ???
jwt.secret=i10a89Vo9y42Soi42qAsDGgRR3UCbetWoCwbCrzN66g=

# ?? ?? ?? (ms ??, ??? 1??)
jwt.expiration_time=3600000

