SELECT * FROM emotions;
SELECT * FROM users;
SELECT * FROM mini_homepages;
SELECT * FROM user_profiles;
SELECT * FROM board;
SELECT * FROM comments;
SELECT * FROM ilchons;
SELECT * FROM visits;
SELECT * FROM bgm;